language: ruby
sudo: false
rvm:
  - 2.1
  - 2.2
  - 2.3.0
install:
  - bundle install --retry=3
script:
  - bundle exec rake test
notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#virtapi"
  email: false
